default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: deployer
  password: 123

development:
  <<: *default
  database: mytodo_dev

test:
  <<: *default
  database: mytodo_test

production:
  <<: *default
  database: mytodo_prod
